import path from "node:path";
import type { Project } from "../core/model.ts";
import { code, linkTarget, manualBlock, tableCell } from "./markdown.ts";

export interface IndexInput {
  projects: Project[];
  /** Index path relative to the root. */
  index: string;
  /** Card path (relative to the root) of each project. */
  cardOf: (project: Project) => string;
  manifestName: string;
  manual: string | undefined;
}

const TOP_LEVEL = "(top level)";
const UNTAGGED = "other";

const compare = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

function folderOf(project: Project): string {
  const slash = project.path.indexOf("/");
  return slash === -1 ? TOP_LEVEL : project.path.slice(0, slash);
}

/** First tag that says more than the folder name. */
function primaryTag(project: Project, folder: string): string {
  return project.tags.find((tag) => tag !== folder) ?? UNTAGGED;
}

function groupBy<T>(items: T[], key: (item: T) => string): Map<string, T[]> {
  const groups = new Map<string, T[]>();
  for (const item of items) {
    const name = key(item);
    groups.set(name, [...(groups.get(name) ?? []), item]);
  }
  return groups;
}

export function renderIndex(input: IndexInput): string {
  const folders = groupBy(input.projects, folderOf);
  const folderNames = [...folders.keys()].sort((a, b) =>
    a === TOP_LEVEL ? -1 : b === TOP_LEVEL ? 1 : compare(a, b),
  );
  const indexDir = path.posix.dirname(input.index);

  const out: string[] = [
    "# Repository index",
    "",
    `<!-- Generated by \`overrepo context\` from ${input.manifestName}. Do not edit, except the manual block at the end. -->`,
    "",
    "This workspace is a meta-repo: each project below is an independent git repository checked out at the listed path.",
    "",
    "**For AI agents:** find the relevant project in this index, then **read its card (linked in the first column) before exploring its directory**. A card summarizes the stack, scripts, structure, internal dependencies and agent instructions of a repository.",
    "",
    `${input.projects.length} project${input.projects.length === 1 ? "" : "s"} in ${folderNames.length} folder${folderNames.length === 1 ? "" : "s"}.`,
    "",
  ];

  for (const folder of folderNames) {
    const projects = folders.get(folder) ?? [];
    out.push(`## ${folder}`, "");
    const groups = groupBy(projects, (project) => primaryTag(project, folder));
    const groupNames = [...groups.keys()].sort((a, b) =>
      a === UNTAGGED ? 1 : b === UNTAGGED ? -1 : compare(a, b),
    );
    for (const group of groupNames) {
      if (groupNames.length > 1) out.push(`### ${group}`, "");
      out.push("| Project | Path | Description | Tags |", "| --- | --- | --- | --- |");
      const rows = [...(groups.get(group) ?? [])].sort((a, b) => compare(a.name, b.name));
      for (const project of rows) {
        const card = linkTarget(path.posix.relative(indexDir, input.cardOf(project)));
        out.push(
          `| [${tableCell(project.name)}](${card}) | ${code(`${project.path}/`)} | ${tableCell(project.desc ?? "")} | ${tableCell(project.tags.join(", "))} |`,
        );
      }
      out.push("");
    }
  }

  return `${out.join("\n").trimEnd()}\n\n${manualBlock(input.manual)}\n`;
}
