import path from "node:path";
import { Document, isSeq } from "yaml";
import type { SummaryConfig } from "../core/model.ts";
import type { Analysis } from "./analyze.ts";
import { code, linkTarget, manualBlock, readmeExcerpt, truncate } from "./markdown.ts";

export interface DependencyLink {
  name: string;
  /** Card path of the other project, relative to the root. */
  card: string;
  via: string;
}

export interface CardInput {
  analysis: Analysis;
  /** Card path relative to the manifest directory. */
  card: string;
  /** Clone path relative to the manifest directory. */
  checkout: string;
  uses: DependencyLink[];
  usedBy: DependencyLink[];
  config: SummaryConfig;
  manual: string | undefined;
}

interface Limits {
  readmeChars: number;
  treeEntries: number;
  scripts: number;
  dependencies: number;
}

const MAX_SCRIPT_COMMAND = 120;

export function frontmatter(data: Record<string, unknown>): string {
  const doc = new Document(data);
  for (const key of Object.keys(data)) {
    const node = doc.get(key, true);
    if (isSeq(node)) node.flow = true;
  }
  return `---\n${doc.toString({ lineWidth: 0 })}---`;
}

function relativeLink(fromFile: string, toRootRelative: string): string {
  return linkTarget(path.posix.relative(path.posix.dirname(fromFile), toRootRelative) || ".");
}

function list(items: string[], limit: number, noun: string): string[] {
  const lines = items.slice(0, limit);
  if (items.length > limit) lines.push(`- … ${items.length - limit} more ${noun}`);
  return lines;
}

function render(input: CardInput, limits: Limits): string {
  const { analysis, card } = input;
  const { project, stack } = analysis;
  const repoLink = (file = "") =>
    relativeLink(card, file ? `${input.checkout}/${file}` : input.checkout) + (file ? "" : "/");
  const out: string[] = [];

  out.push(
    frontmatter({
      name: project.name,
      path: project.path,
      ...(project.url ? { url: project.url } : {}),
      tags: project.tags,
      cloned: analysis.cloned,
      "generated-by": "overrepo",
    }),
    "",
    "<!-- Generated by `overrepo context`. Edit overrepo.yaml or the manual block at the end, not this file. -->",
    "",
    `# ${project.name}`,
    "",
  );
  if (project.desc) out.push(project.desc, "");

  const facts = [`- **Path:** [${code(`${project.path}/`)}](${repoLink()})`];
  if (project.url) facts.push(`- **Repository:** ${code(project.url)}`);
  if (project.tags.length > 0) facts.push(`- **Tags:** ${project.tags.join(", ")}`);
  out.push(...facts, "");

  if (!analysis.cloned) {
    out.push(
      "> **Not cloned locally.** This card only contains manifest data; run `overrepo sync` then `overrepo context` to enrich it.",
      "",
    );
  }

  if (analysis.agentFiles.length > 0) {
    out.push(
      "## Agent instructions",
      "",
      "This repository ships its own instructions for AI agents. Read them before working inside it:",
      "",
      ...analysis.agentFiles.map((file) => `- [${file}](${repoLink(file)})`),
      "",
    );
  }

  const stackLines = (
    [
      ["Languages", stack.languages],
      ["Frameworks", stack.frameworks],
      ["Package managers", stack.packageManagers],
      ["Runtimes", stack.runtimes],
      ["Tooling", stack.tools],
      ["Notes", stack.notes],
    ] as const
  )
    .filter(([, values]) => values.length > 0)
    .map(([label, values]) => `- **${label}:** ${values.join(", ")}`);
  if (stackLines.length > 0) out.push("## Stack", "", ...stackLines, "");

  if (analysis.scripts.length > 0 && limits.scripts > 0) {
    const scripts = analysis.scripts.map((script) => {
      const invocation = code(`${script.runner} ${script.name}`);
      return script.cmd
        ? `- ${invocation} — ${code(truncate(script.cmd, MAX_SCRIPT_COMMAND))}`
        : `- ${invocation}`;
    });
    out.push("## Scripts", "", ...list(scripts, limits.scripts, "scripts"), "");
  }

  if ((input.uses.length > 0 || input.usedBy.length > 0) && limits.dependencies > 0) {
    out.push("## Internal dependencies", "");
    const line = (link: DependencyLink) =>
      `- [${link.name}](${relativeLink(card, link.card)}) — ${link.via}`;
    if (input.uses.length > 0)
      out.push("Uses:", "", ...list(input.uses.map(line), limits.dependencies, "projects"), "");
    if (input.usedBy.length > 0)
      out.push(
        "Used by:",
        "",
        ...list(input.usedBy.map(line), limits.dependencies, "projects"),
        "",
      );
  }

  if (analysis.keyFiles.length > 0) {
    out.push(
      "## Key files",
      "",
      ...analysis.keyFiles.map((file) => `- [${file}](${repoLink(file)})`),
      "",
    );
  }

  if (analysis.tree.length > 0 && limits.treeEntries > 0) {
    const shown = analysis.tree.slice(0, limits.treeEntries);
    if (analysis.tree.length > shown.length)
      shown.push(`… ${analysis.tree.length - shown.length} more entries`);
    out.push("## Structure", "", "```text", ...shown, "```", "");
  }

  if (analysis.readme && analysis.readmeFile && limits.readmeChars > 0) {
    const excerpt = readmeExcerpt(analysis.readme, limits.readmeChars);
    if (excerpt.text) {
      out.push(`## README (excerpt)`, "", excerpt.text, "");
      if (excerpt.truncated)
        out.push(
          `_… truncated, see [${analysis.readmeFile}](${repoLink(analysis.readmeFile)})._`,
          "",
        );
    }
  }

  return out.join("\n");
}

/**
 * Renders a card whose generated part stays under `config.maxBytes`, shrinking the
 * least essential sections first (README, then tree, scripts, dependencies).
 */
export function renderCard(input: CardInput): string {
  const { config } = input;
  const limits: Limits = {
    readmeChars: config.readmeMaxChars,
    treeEntries: config.treeMaxEntries,
    scripts: 60,
    dependencies: 50,
  };
  let body = render(input, limits);
  const size = () => Buffer.byteLength(body);

  while (size() > config.maxBytes) {
    const overflow = size() - config.maxBytes;
    if (limits.readmeChars > 0)
      limits.readmeChars =
        limits.readmeChars > overflow + 200 ? limits.readmeChars - overflow - 200 : 0;
    else if (limits.treeEntries > 10)
      limits.treeEntries = Math.max(10, Math.floor(limits.treeEntries / 2));
    else if (limits.scripts > 10) limits.scripts = Math.max(10, Math.floor(limits.scripts / 2));
    else if (limits.dependencies > 10)
      limits.dependencies = Math.max(10, Math.floor(limits.dependencies / 2));
    else break;
    body = render(input, limits);
  }

  if (size() > config.maxBytes) {
    const cut = Buffer.from(body).subarray(0, config.maxBytes).toString("utf8").replace(/�$/, "");
    body = `${cut.slice(0, cut.lastIndexOf("\n"))}\n\n_… card truncated to ${config.maxBytes} bytes._\n`;
  }

  return `${body.trimEnd()}\n\n${manualBlock(input.manual)}\n`;
}
